cimport hse_limits

KVS_COUNT_MAX = hse_limits.HSE_KVS_COUNT_MAX
KVS_KLEN_MAX = hse_limits.HSE_KVS_KLEN_MAX
KVS_VLEN_MAX = hse_limits.HSE_KVS_VLEN_MAX
KVS_MAX_PFXLEN = hse_limits.HSE_KVS_MAX_PFXLEN
KVS_NAME_LEN_MAX = hse_limits.HSE_KVS_NAME_LEN_MAX
