# Do not use this until mesonpep517 improves
[project]
name = "hse-python" # https://gitlab.com/thiblahute/mesonpep517/-/issues/16
version = "2.1.0"
description = "HSE is a fast embeddable key-value store designed for SSDs and persistent memory."
maintainers = [
	{ name = "Micron HSE", email = "hse@micron.com" },
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6"
# https://gitlab.com/thiblahute/mesonpep517/-/issues/15
# keywords = [
	# "micron",
	# "hse",
	# "key",
	# "value"
	# "database"
	# "bindings",
	# "heterogeneous",
	# "memory",
	# "storage",
	# "engine",
# ]
classifiers = [
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: POSIX :: Linux",
	"Programming Language :: Cython",
	"Programming Language :: Python :: 3 :: Only",
	"Topic :: Database",
	"Topic :: Database :: Database Engines/Servers",
	"Typing :: Typed",
]

[project.urls]
repohome = "https://github.com/hse-project/hse-python"
projecthome = "https://hse-project.github.io/"

[project.optional-dependencies]
dev = [
	"meson >= 0.58.2",
	"black >= 20.8b1",
	"ninja >= 1.10.0",
	"Cython >= 0.29.23",
	"pytest >= 6.2.4",
	"pytest-tap >= 3.2",
]

[build-system]
requires = [
	"meson >= 0.58.2",
	"ninja >= 1.10.0",
	"mesonpep517 @ git+https://gitlab.com/thiblahute/mesonpep517@a11ee772513071198d02d555ac26a3c32e10608f",
	"build >= 0.5.1",
	"Cython >= 0.29.23",
	"pytest >= 6.2.4",
	"pytest-tap >= 3.2",
]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
meson-options = [
	"-Dtests=false",
]
