name: Black

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - "**.pyi"

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        python3 -m pip install black

    - name: Check
      continue-on-error: true
      run: |
        black --check ./
