name: Black

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - "**.pyi"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: |
        python3 -m pip install black

    - name: Check
      continue-on-error: true
      run: |
        black --check ./
