name: Black

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.py"
      - "**.pyi"

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
