name: Builds

on:
  push:
    branches:
      - master
      - v*.*
    paths-ignore:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/**"
      - "!.github/workflows/builds.yaml"
      - .coveragerc
      - .gitattributes
      - .github/dependabot.yaml
      - .gitignore
      - .shellcheckrc
      - LICENSE
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/**"
      - "!.github/workflows/builds.yaml"
      - .coveragerc
      - .gitattributes
      - .github/dependabot.yaml
      - .gitignore
      - .shellcheckrc
      - LICENSE

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

env:
  MESON_TESTTHREADS: 1

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.image-tag }}
    strategy:
      fail-fast: false
      matrix:
        image-tag: ["18.04", "20.04"]
        buildtype: [release, debug]
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Initialize
        run: |
          apt-get -y update
          apt-get -y install git build-essential ninja-build pkg-config \
            libbsd-dev libmicrohttpd-dev liburcu-dev libyaml-dev liblz4-dev \
            libcurl4-openssl-dev python3-dev python3-pip

      - name: Checkout hse-python
        uses: actions/checkout@v3

      - name: Determine branches
        id: determine-branches
        run: |
          for p in hse; do
            [ "$GITHUB_EVENT_NAME" = "pull_request" ] && git ls-remote \
              --exit-code --heads "https://github.com/hse-project/$p.git" \
              "$GITHUB_HEAD_REF" > /dev/null
            if [ $? -eq 0 ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
              echo "::set-output name=$p::$GITHUB_HEAD_REF"
            else
              echo "::set-output name=$p::master"
            fi
          done

      - name: Checkout HSE
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse
          path: subprojects/hse
          ref: ${{ steps.determine-branches.outputs.hse }}

      - name: Get Meson on ubuntu-18.04
        if: ${{ matrix.image-tag == '18.04' }}
        run: |
          apt-get -y install python3.7
          python3.7 -m pip install meson Cython

      - name: Get Meson on ubuntu-20.04
        if: ${{ matrix.image-tag == '20.04' }}
        run: |
          python3 -m pip install meson Cython

      - name: Setup
        run: |
          meson builddir --buildtype=${{ matrix.buildtype }} --werror

      - name: Build
        run: |
          ninja -C builddir

      - name: Test
        run: |
          meson test -C builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.image-tag }}-${{ matrix.buildtype }}
          path: builddir/meson-logs/

  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:${{ matrix.image-tag }}
    strategy:
      fail-fast: false
      matrix:
        image-tag: [36]
        buildtype: [release, debug]

    steps:
      - name: Initialize
        run: |
          dnf group install -y --with-optional \
            "C Development Tools and Libraries"
          dnf install -y git ninja-build meson pkg-config libmicrohttpd-devel \
            userspace-rcu-devel libyaml-devel lz4-devel libbsd-devel \
            libcurl-devel libxml2-devel libxslt-devel \
            python3-devel python3-Cython

      - name: Checkout hse-python
        uses: actions/checkout@v3

      - name: Determine branches
        id: determine-branches
        run: |
          for p in hse; do
            [ "$GITHUB_EVENT_NAME" = "pull_request" ] && git ls-remote \
              --exit-code --heads "https://github.com/hse-project/$p.git" \
              "$GITHUB_HEAD_REF" > /dev/null
            if [ $? -eq 0 ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
              echo "::set-output name=$p::$GITHUB_HEAD_REF"
            else
              echo "::set-output name=$p::master"
            fi
          done

      - name: Checkout HSE
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse
          path: subprojects/hse
          ref: ${{ steps.determine-branches.outputs.hse }}

      - name: Setup
        run: |
          meson builddir --buildtype=${{ matrix.buildtype }} --werror

      - name: Build
        run: |
          ninja -C builddir

      - name: Test
        run: |
          meson test -C builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.image-tag }}-${{ matrix.buildtype }}
          path: builddir/meson-logs/

  almalinux:
    runs-on: ubuntu-latest
    container:
      image: almalinux:${{ matrix.image-tag }}
    strategy:
      fail-fast: false
      matrix:
        image-tag: [8]
        buildtype: [release, debug]

    steps:
      - name: Initialize
        run: |
          dnf install -y sudo dnf-plugins-core epel-release
          dnf config-manager --set-enabled powertools
          dnf group install -y --with-optional "Development Tools"
          dnf install -y git ninja-build libmicrohttpd-devel \
            userspace-rcu-devel libyaml-devel lz4-devel libbsd-devel \
            libcurl-devel libxml2 libxslt python36 python36-devel
          python3 -m pip install meson Cython

      - name: Checkout hse-python
        uses: actions/checkout@v3

      - name: Determine branches
        id: determine-branches
        run: |
          for p in hse; do
            [ "$GITHUB_EVENT_NAME" = "pull_request" ] && git ls-remote \
              --exit-code --heads "https://github.com/hse-project/$p.git" \
              "$GITHUB_HEAD_REF" > /dev/null
            if [ $? -eq 0 ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
              echo "::set-output name=$p::$GITHUB_HEAD_REF"
            else
              echo "::set-output name=$p::master"
            fi
          done

      - name: Checkout HSE
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse
          path: subprojects/hse
          ref: ${{ steps.determine-branches.outputs.hse }}

      - name: Setup
        run: |
          meson builddir --buildtype=${{ matrix.buildtype }} --werror

      - name: Build
        run: |
          ninja -C builddir

      - name: Test
        run: |
          meson test -C builddir --setup=ci --print-errorlogs --no-stdsplit

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.image-tag }}-${{ matrix.buildtype }}
          path: builddir/meson-logs/

  architectures:
    runs-on: ubuntu-latest
    container:
      image: debian:11
    strategy:
      fail-fast: false
      matrix:
        buildtype: [release, debug]
        arch: [s390x]

    steps:
      - name: Initialize
        run: |
          dpkg --add-architecture ${{ matrix.arch }}
          apt-get -y update
          apt-get -y install git python3 python3-pip pkg-config ninja-build \
            build-essential crossbuild-essential-${{ matrix.arch }} \
            libpython3-dev:${{ matrix.arch }} liburcu-dev:${{ matrix.arch }} \
            libcurl4-openssl-dev:${{ matrix.arch }} \
            libbsd-dev:${{ matrix.arch }} libmicrohttpd-dev:${{ matrix.arch }} \
            libyaml-dev:${{ matrix.arch }}
          python3 -m pip install meson Cython

      - name: Checkout hse-python
        uses: actions/checkout@v3

      - name: Determine branches
        id: determine-branches
        run: |
          for p in hse; do
            [ "$GITHUB_EVENT_NAME" = "pull_request" ] && git ls-remote \
              --exit-code --heads "https://github.com/hse-project/$p.git" \
              "$GITHUB_HEAD_REF" > /dev/null
            if [ $? -eq 0 ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
              echo "::set-output name=$p::$GITHUB_HEAD_REF"
            else
              echo "::set-output name=$p::master"
            fi
          done

      - name: Checkout HSE
        uses: actions/checkout@v3
        with:
          repository: hse-project/hse
          path: subprojects/hse
          ref: ${{ steps.determine-branches.outputs.hse }}

      - name: Setup
        run: |
          meson builddir --cross-file cross/${{ matrix.arch }}.ini \
            --cross-file cross/common.ini --buildtype=${{ matrix.buildtype }} \
            --werror

      - name: Build
        run: |
          ninja -C builddir

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.arch }}-${{ matrix.buildtype }}
          path: |
            builddir/meson-logs/
