# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.

name: Flake8

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - "**.pyi"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout hse-python
      uses: actions/checkout@v4

    - name: Setup
      run: |
        python3 -m pip install flake8 flake8-pyi

    - name: Check
      continue-on-error: true
      run: |
        flake8 .
