# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.

name: REUSE

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout hse-python
      uses: actions/checkout@v3

    - name: REUSE
      uses: fsfe/reuse-action@v1
