name: ShellCheck

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - "**.sh"
      - "scripts/git-hooks/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: fedora:36
      options: --privileged -v /usr/src:/usr/src -v /lib/modules:/lib/modules

    steps:
      - uses: actions/checkout@v3

      - name: Initialize
        run: |
          dnf install -y findutils ShellCheck

      - name: Lint
        run: |
          ./scripts/dev/shellcheck.sh
