# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.

name: ShellCheck

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.sh"
      - .github/workflows/shellcheck.yaml

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
