# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.

name: ShellCheck

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - "**.sh"
      - .github/workflows/shellcheck.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: fedora:36

    steps:
      - name: Checkout hse-python
        uses: actions/checkout@v3

      - name: Initialize
        run: |
          dnf install -y findutils ShellCheck

      - name: Lint
        run: |
          ./scripts/dev/shellcheck.sh
